[workspace]
authors = ["Giovanni Dejan <giovanni.dejan@binus.ac.id>"]
channels = ["conda-forge"]
name = "wqf7006-malaysian-sign-language"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
preprocess = "python3 01_preprocess.py"
generate_npy = "python3 02_generate_npy.py"
train = "python3 03_train.py"
server = "python3 server.py"

[system-requirements]
cuda = "12.0"

[dependencies]
python = ">=3.12, <3.13"
pytorch-gpu = "*"
torchvision = ">=0.24.1, <0.25"
numpy = ">=1,<2"
matplotlib = ">=3.10.8,<4"
jupyter = ">=1.1.1,<2"
ipywidgets = ">=7,<8"
jupyterlab = ">=4.5.0,<5"
pixi-kernel = ">=0.7.1,<0.8"
opencv = ">=4.12.0,<5"
gradio = ">=5.49.1,<6"
keras = ">=3.12.0,<4"
scikit-learn = ">=1.8.0,<2"

[pypi-dependencies]
mediapipe = ">=0.10.21, <0.11"
