[workspace]
authors = ["Giovanni Dejan <giovanni.dejan@binus.ac.id>"]
channels = ["conda-forge"]
name = "wqf7006-malaysian-sign-language"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
main = "python3 main.py"
train = "python3 train.py"
lab = "jupyter lab --no-browser"

[system-requirements]
cuda = "12.0"

[dependencies]
python = ">=3.12, <3.13"
pytorch-gpu = "*"
torchvision = ">=0.24.1, <0.25"
numpy = ">=1,<2"
matplotlib = ">=3.10.8,<4"
jupyter = ">=1.1.1,<2"
ipywidgets = ">=7,<8"
jupyterlab = ">=4.5.0,<5"
pixi-kernel = ">=0.7.1,<0.8"
opencv = ">=4.12.0,<5"

[pypi-dependencies]
mediapipe = ">=0.10.21, <0.11"
